import { App_State } from "./types";

export const initial_state: App_State = {
  stats: null,
  slides: [],
  ads_and_data: null,
  ads_and_data_is_valid: false,
  app_settings: null,
  app_settings_is_valid: false,
  comment: null,
  comment_is_valid: false,
  direct_message: null,
  direct_message_is_valid: false,
  income_plus_wallet_transactions: null,
  income_plus_wallet_transactions_is_valid: false,
  location_review: null,
  location_review_is_valid: false,
  post: null,
  post_is_valid: false,
  profile: null,
  profile_is_valid: false,
  tiktok_shop: null,
  tiktok_shop_is_valid: false,
  tiktok_live: null,
  tiktok_live_is_valid: false,
  your_activity: null,
  your_activity_is_valid: false,
  error: null,
  view_state: "upload",
  is_loading: false,
  is_demo_mode: false,
  is_exporting: false,
};
