import { Profile_Definition } from "@/stores/calculate_user_profile";

export const PROFILES: Profile_Definition[] = [
  // low consumption
  {
    combination_key: "low_low_low_low",
    profile_name: "App Ghost",
    profile_description: "Here but barely. Opens TikTok like a solar eclipse, rare and brief.",
    profile_image: "/user_profiles/app_ghost.png",
  },
  {
    combination_key: "low_low_low_medium",
    profile_name: "Occasional Post Phantom",
    profile_description:
      "Hardly watches, sometimes drops a post then vanishes. Treats TikTok like a message in a bottle.",
    profile_image: "/user_profiles/occasional_post_phantom.png",
  },
  {
    combination_key: "low_low_low_high",
    profile_name: "Creator Only",
    profile_description: "Posts away without peeking at anyone else. Main character energy with no audience scouting.",
    profile_image: "/user_profiles/creator_only.png",
  },
  {
    combination_key: "low_low_medium_low",
    profile_name: "Mystery Forwarder",
    profile_description: "Barely watches, still forwards the good stuff somehow. Human push notification.",
    profile_image: "/user_profiles/mystery_forwarder.png",
  },
  {
    combination_key: "low_low_medium_medium",
    profile_name: "Off-App Producer",
    profile_description: "Creates and forwards more than they watch. Runs on vibes and outside recommendations.",
    profile_image: "/user_profiles/off_app_producer.png",
  },
  {
    combination_key: "low_low_medium_high",
    profile_name: "Upload Hermit",
    profile_description: "Builds content caves and never looks outside. Posts boldly, watches rarely.",
    profile_image: "/user_profiles/upload_hermit.png",
  },
  {
    combination_key: "low_low_high_low",
    profile_name: "Forward Frenzy Phantom",
    profile_description:
      "Never sticks around to watch, launches links like confetti. Your DM stays busy because of them.",
    profile_image: "/user_profiles/forward_frenzy_phantom.png",
  },
  {
    combination_key: "low_low_high_medium",
    profile_name: "Share-First Maker",
    profile_description: "Ships clips and crafts a few, hardly ever scrolls. Courier by day, creator by night.",
    profile_image: "/user_profiles/share_first_maker.png",
  },
  {
    combination_key: "low_low_high_high",
    profile_name: "Broadcast Hermit",
    profile_description: "Cranks out posts and lives, barely peeks at the feed. Talk show host to themselves.",
    profile_image: "/user_profiles/broadcast_hermit.png",
  },
  {
    combination_key: "low_medium_low_low",
    profile_name: "Sparse Hype Tapper",
    profile_description: "Shows up rarely, then likes and comments like it matters. Vanishes again like mist.",
    profile_image: "/user_profiles/sparse_hype_tapper.png",
  },
  {
    combination_key: "low_medium_low_medium",
    profile_name: "Selective Hype Crafter",
    profile_description:
      "Drops a few posts and thoughtful taps, barely scrolls. Choosy with their time, generous with reactions.",
    profile_image: "/user_profiles/selective_hype_crafter.png",
  },
  {
    combination_key: "low_medium_low_high",
    profile_name: "Like-Light Poster",
    profile_description: "Uploads a lot, hardly watches others. Engages a bit then sprints back to filming.",
    profile_image: "/user_profiles/like_light_poster.png",
  },
  {
    combination_key: "low_medium_medium_low",
    profile_name: "Rare Scroll Rallier",
    profile_description: "Opens rarely, rallies the group with shares and comments. Quality over quantity energy.",
    profile_image: "/user_profiles/rare_scroll_rallier.png",
  },
  {
    combination_key: "low_medium_medium_medium",
    profile_name: "Part-Time Powerhouse",
    profile_description: "Skims the feed, then does a bit of everything else. Efficient chaos in a tiny window.",
    profile_image: "/user_profiles/part_time_powerhouse.png",
  },
  {
    combination_key: "low_medium_medium_high",
    profile_name: "Studio Tunnel Vision",
    profile_description: "All gas on posting, little time for watching. Talks to the camera like it owes rent.",
    profile_image: "/user_profiles/studio_tunnel_vision.png",
  },
  {
    combination_key: "low_medium_high_low",
    profile_name: "Chatty Link Launcher",
    profile_description: "Does not watch much, still blasts DMs and adds zesty comments. The group chat stays fed.",
    profile_image: "/user_profiles/chatty_link_launcher.png",
  },
  {
    combination_key: "low_medium_high_medium",
    profile_name: "Share Storm Artisan",
    profile_description:
      "Crafts some clips, comments plenty, hurls links like frisbees. Barely scrolls, still stays viral in chats.",
    profile_image: "/user_profiles/share_storm_artisan.png",
  },
  {
    combination_key: "low_medium_high_high",
    profile_name: "Post-First Dynamo",
    profile_description: "Goes live and posts nonstop, skims nothing. Audience yes, timeline no.",
    profile_image: "/user_profiles/post_first_dynamo.png",
  },
  {
    combination_key: "low_high_low_low",
    profile_name: "Hit-and-Hype",
    profile_description: "Shows up late, likes and comments like a superfan. Then disappears without sharing.",
    profile_image: "/user_profiles/hit_and_hype.png",
  },
  {
    combination_key: "low_high_low_medium",
    profile_name: "Selective Superfan Maker",
    profile_description: "Posts sometimes, barely scrolls, leaves big reactions when present. Quality claps only.",
    profile_image: "/user_profiles/selective_superfan_maker.png",
  },
  {
    combination_key: "low_high_low_high",
    profile_name: "Commentator Creator",
    profile_description: "Posts like a pro, almost never watches. When they peek, they drop thunder in the comments.",
    profile_image: "/user_profiles/commentator_creator.png",
  },
  {
    combination_key: "low_high_medium_low",
    profile_name: "Drive-By Hype Courier",
    profile_description: "Rarely watches, still blasts praise and forwards gems. Like a parade that never stops.",
    profile_image: "/user_profiles/drive_by_hype_courier.png",
  },
  {
    combination_key: "low_high_medium_medium",
    profile_name: "Busy Bee Minimalist",
    profile_description: "Does a bit of everything with high-energy reactions, hardly scrolls. Bees do not binge.",
    profile_image: "/user_profiles/busy_bee_minimalist.png",
  },
  {
    combination_key: "low_high_medium_high",
    profile_name: "Upload Applause Magnet",
    profile_description: "Lives and posts often, feed barely touched. Relies on cheers, not scrolling.",
    profile_image: "/user_profiles/upload_applause_magnet.png",
  },
  {
    combination_key: "low_high_high_low",
    profile_name: "Chat Orbit Sprinter",
    profile_description: "Shares like a confetti cannon and comments nonstop, barely watches. The group chat MVP.",
    profile_image: "/user_profiles/chat_orbit_sprinter.png",
  },
  {
    combination_key: "low_high_high_medium",
    profile_name: "Viral Party Courier",
    profile_description: "Hurls links and hype, drops a few posts too. Scrolling is optional, social is mandatory.",
    profile_image: "/user_profiles/viral_party_courier.png",
  },
  {
    combination_key: "low_high_high_high",
    profile_name: "Stage-Only Star",
    profile_description: "Creates and goes live constantly, feed is a stranger. Spotlight stays on them.",
    profile_image: "/user_profiles/stage_only_star.png",
  },
  // medium consumption
  {
    combination_key: "medium_low_low_low",
    profile_name: "Casual Scroller",
    profile_description: "Watches here and there, leaves no trace. Quiet footprints on an endless feed.",
    profile_image: "/user_profiles/casual_scroller.png",
  },
  {
    combination_key: "medium_low_low_medium",
    profile_name: "Silent Builder",
    profile_description: "Browses breezily, then posts occasionally. Keeps thoughts in drafts not comments.",
    profile_image: "/user_profiles/silent_builder.png",
  },
  {
    combination_key: "medium_low_low_high",
    profile_name: "Studio Lurker",
    profile_description: "Knows the trends, rarely reacts, posts a bunch. Ghost in the comments, loud in the uploads.",
    profile_image: "/user_profiles/studio_lurker.png",
  },
  {
    combination_key: "medium_low_medium_low",
    profile_name: "Link Whisper Walker",
    profile_description: "Watches a bit, quietly forwards a few. Minimal taps, maximal stealth.",
    profile_image: "/user_profiles/link_whisper_walker.png",
  },
  {
    combination_key: "medium_low_medium_medium",
    profile_name: "Balanced Background Sender",
    profile_description: "Scrolls calmly, shares some, posts sometimes. Operates on quiet mode.",
    profile_image: "/user_profiles/balanced_background_sender.png",
  },
  {
    combination_key: "medium_low_medium_high",
    profile_name: "Broadcast Botanist",
    profile_description: "Grows lots of posts, prunes reactions. Waters friends with steady shares.",
    profile_image: "/user_profiles/broadcast_botanist.png",
  },
  {
    combination_key: "medium_low_high_low",
    profile_name: "DM Fire Hose",
    profile_description: "Scrolls then blasts links everywhere. Talks with forwards not words.",
    profile_image: "/user_profiles/dm_fire_hose.png",
  },
  {
    combination_key: "medium_low_high_medium",
    profile_name: "Share Rocket Crafter",
    profile_description: "Builds a few videos, launches links at warp speed. Taps are rare, DMs are busy.",
    profile_image: "/user_profiles/share_rocket_crafter.png",
  },
  {
    combination_key: "medium_low_high_high",
    profile_name: "Hype Courier Producer",
    profile_description: "Posts plenty and forwards more, barely reacts. Movement over musing.",
    profile_image: "/user_profiles/hype_courier_producer.png",
  },
  {
    combination_key: "medium_medium_low_low",
    profile_name: "Steady Feed Noddler",
    profile_description: "Watches, likes, and comments at a calm pace. Keeps goodies to themselves.",
    profile_image: "/user_profiles/steady_feed_noddler.png",
  },
  {
    combination_key: "medium_medium_low_medium",
    profile_name: "Even Keel Creator",
    profile_description: "Balanced scrolling with balanced posting, mild reactions. Sharing is not their hobby.",
    profile_image: "/user_profiles/even_keel_creator.png",
  },
  {
    combination_key: "medium_medium_low_high",
    profile_name: "Studio Metronome",
    profile_description: "Regular viewer, prolific poster, steady reactions. Sharing stays on pause.",
    profile_image: "/user_profiles/studio_metronome.png",
  },
  {
    combination_key: "medium_medium_medium_low",
    profile_name: "All-Round Window Shopper",
    profile_description: "Does a bit of everything, rarely posts. Tries it all, avoids the spotlight.",
    profile_image: "/user_profiles/all_round_window_shopper.png",
  },
  {
    combination_key: "medium_medium_medium_medium",
    profile_name: "Balanced Byte Buddy",
    profile_description: "Even vibes across the board. The algorithm shrugs and smiles.",
    profile_image: "/user_profiles/balanced_byte_buddy.png",
  },
  {
    combination_key: "medium_medium_medium_high",
    profile_name: "Busy Feed Foreman",
    profile_description: "Watches and reacts steadily, builds content like a worksite. Hard hat, soft heart.",
    profile_image: "/user_profiles/busy_feed_foreman.png",
  },
  {
    combination_key: "medium_medium_high_low",
    profile_name: "Chat Superconductor",
    profile_description: "Keeps the group chat electrified with links. Rarely posts, often passes the vibe.",
    profile_image: "/user_profiles/chat_superconductor.png",
  },
  {
    combination_key: "medium_medium_high_medium",
    profile_name: "Share Stream Pilot",
    profile_description: "Flies the DM plane, posts on a schedule. Smooth reactions, smooth landings.",
    profile_image: "/user_profiles/share_stream_pilot.png",
  },
  {
    combination_key: "medium_medium_high_high",
    profile_name: "Link-Loud Producer",
    profile_description: "Creates a lot and shares even more. Comments keep pace like drumbeats.",
    profile_image: "/user_profiles/link_loud_producer.png",
  },
  {
    combination_key: "medium_high_low_low",
    profile_name: "Comment Comet",
    profile_description: "Streaks through videos dropping hot takes and hearts. Keeps the gems to themselves.",
    profile_image: "/user_profiles/comment_comet.png",
  },
  {
    combination_key: "medium_high_low_medium",
    profile_name: "Clapback Craftsperson",
    profile_description: "Builds some posts and floods threads with replies. Shares rarely, opinions often.",
    profile_image: "/user_profiles/clapback_craftsperson.png",
  },
  {
    combination_key: "medium_high_low_high",
    profile_name: "Studio Hype Engine",
    profile_description: "Cranks out uploads and turbo comments. Sharing is the only quiet button.",
    profile_image: "/user_profiles/studio_hype_engine.png",
  },
  {
    combination_key: "medium_high_medium_low",
    profile_name: "Social Reactor",
    profile_description: "Energizes feeds with comments and shares. Posts infrequently, presence is loud.",
    profile_image: "/user_profiles/social_reactor.png",
  },
  {
    combination_key: "medium_high_medium_medium",
    profile_name: "Buzz Circuit Maker",
    profile_description: "Builds clips and runs lively comment threads. Sharing sits at a happy middle.",
    profile_image: "/user_profiles/buzz_circuit_maker.png",
  },
  {
    combination_key: "medium_high_medium_high",
    profile_name: "Content Hype Cycler",
    profile_description: "Posts hard, hypes harder. Sharing keeps the loop spinning.",
    profile_image: "/user_profiles/content_hype_cycler.png",
  },
  {
    combination_key: "medium_high_high_low",
    profile_name: "Share Parade Captain",
    profile_description:
      "Loves to pass videos and cheer loudly, posting can wait. The algorithm hears their clap from miles away.",
    profile_image: "/user_profiles/share_parade_captain.png",
  },
  {
    combination_key: "medium_high_high_medium",
    profile_name: "DM Confetti Champ",
    profile_description: "Sprays links and reactions with glee, posts a bit too. Every chat becomes a watch party.",
    profile_image: "/user_profiles/dm_confetti_champ.png",
  },
  {
    combination_key: "medium_high_high_high",
    profile_name: "Party Feed Ringleader",
    profile_description:
      "Shares everything and hypes everyone, creates like a festival. The For You Page feels like their event.",
    profile_image: "/user_profiles/party_feed_ringleader.png",
  },
  // high consumption
  {
    combination_key: "high_low_low_low",
    profile_name: "Silent Lurker",
    profile_description: "Watches it all, touches nothing. A ghost in the endless scroll.",
    profile_image: "/user_profiles/silent_lurker.png",
  },
  {
    combination_key: "high_low_low_medium",
    profile_name: "Watcher With Workshop",
    profile_description: "Binges quietly, then posts sometimes. Opinions in stealth mode, uploads in daylight.",
    profile_image: "/user_profiles/watcher_with_workshop.png",
  },
  {
    combination_key: "high_low_low_high",
    profile_name: "Binge and Build",
    profile_description: "Studies the feed like homework, then uploads like a machine. Leaves almost no fingerprints.",
    profile_image: "/user_profiles/binge_and_build.png",
  },
  {
    combination_key: "high_low_medium_low",
    profile_name: "Quiet Link Librarian",
    profile_description: "Watches tons, curates a few shares. Shushes the like button.",
    profile_image: "/user_profiles/quiet_link_librarian.png",
  },
  {
    combination_key: "high_low_medium_medium",
    profile_name: "Calm Feed Curator",
    profile_description: "Sifts through piles of videos, shares some, posts some. Drama-free thumbs.",
    profile_image: "/user_profiles/calm_feed_curator.png",
  },
  {
    combination_key: "high_low_medium_high",
    profile_name: "Studio Sifter Supreme",
    profile_description: "Binges and cherry-picks what to share, posts a lot. Reaction light, output heavy.",
    profile_image: "/user_profiles/studio_sifter_supreme.png",
  },
  {
    combination_key: "high_low_high_low",
    profile_name: "Forward Fountain",
    profile_description: "Soaks up the feed then sprays DMs all day. Rarely taps like, always taps send.",
    profile_image: "/user_profiles/forward_fountain.png",
  },
  {
    combination_key: "high_low_high_medium",
    profile_name: "Viral Mail Maestro",
    profile_description: "Watches everything, forwards favorites, posts sometimes. Quiet thumbs, loud outbox.",
    profile_image: "/user_profiles/viral_mail_maestro.png",
  },
  {
    combination_key: "high_low_high_high",
    profile_name: "Broadcast Postman",
    profile_description: "Posts plenty and delivers links nonstop. Scrolls are study halls.",
    profile_image: "/user_profiles/broadcast_postman.png",
  },
  {
    combination_key: "high_medium_low_low",
    profile_name: "Thoughtful Lurker Lite",
    profile_description: "Binges hard, adds measured reactions. Keeps discoveries tucked away.",
    profile_image: "/user_profiles/thoughtful_lurker_lite.png",
  },
  {
    combination_key: "high_medium_low_medium",
    profile_name: "Steady Stream Crafter",
    profile_description: "Watches a lot, comments some, posts sometimes. Sharing is on a leash.",
    profile_image: "/user_profiles/steady_stream_crafter.png",
  },
  {
    combination_key: "high_medium_low_high",
    profile_name: "Trend Scholar Producer",
    profile_description: "Studies everything, posts heavily, reacts with restraint. Classroom of the For You Page.",
    profile_image: "/user_profiles/trend_scholar_producer.png",
  },
  {
    combination_key: "high_medium_medium_low",
    profile_name: "Curious Chat Conduit",
    profile_description: "Eats up the feed, offers gentle likes, passes links at a steady pace. Posting is rare.",
    profile_image: "/user_profiles/curious_chat_conduit.png",
  },
  {
    combination_key: "high_medium_medium_medium",
    profile_name: "Well-Rounded Binger",
    profile_description: "Consumes a feast, does a bit of everything else. Full plate, balanced bites.",
    profile_image: "/user_profiles/well_rounded_binger.png",
  },
  {
    combination_key: "high_medium_medium_high",
    profile_name: "Production Power Scroller",
    profile_description: "Scrolls endlessly then heads to the studio. Reactions moderate, output major.",
    profile_image: "/user_profiles/production_power_scroller.png",
  },
  {
    combination_key: "high_medium_high_low",
    profile_name: "DM Jet Stream",
    profile_description: "High-altitude watcher with gusty shares. Posts rarely, tailwinds of comments.",
    profile_image: "/user_profiles/dm_jet_stream.png",
  },
  {
    combination_key: "high_medium_high_medium",
    profile_name: "Sharing Skyline Pilot",
    profile_description: "Binges tall stacks, forwards often, posts sometimes. Comments cruise at mid level.",
    profile_image: "/user_profiles/sharing_skyline_pilot.png",
  },
  {
    combination_key: "high_medium_high_high",
    profile_name: "All-Access Broadcaster",
    profile_description: "Sees everything, sends everything, makes everything. Reaction dial sits at mid.",
    profile_image: "/user_profiles/all_access_broadcaster.png",
  },
  {
    combination_key: "high_high_low_low",
    profile_name: "Interaction Monster",
    profile_description: "Watches and reacts to everything, never posts. Comment section is their stage.",
    profile_image: "/user_profiles/interaction_monster.png",
  },
  {
    combination_key: "high_high_low_medium",
    profile_name: "Hype Critic Creator",
    profile_description: "Top-tier watcher with turbo opinions, posts sometimes. Sharing is a rare treat.",
    profile_image: "/user_profiles/hype_critic_creator.png",
  },
  {
    combination_key: "high_high_low_high",
    profile_name: "Studio Superfan",
    profile_description: "Binges and argues passionately, uploads a lot. Sharing is the quiet kid.",
    profile_image: "/user_profiles/studio_superfan.png",
  },
  {
    combination_key: "high_high_medium_low",
    profile_name: "Engagement Juggernaut",
    profile_description: "Watches and hypes non-stop, rarely creates. The like button calls them boss.",
    profile_image: "/user_profiles/engagement_juggernaut.png",
  },
  {
    combination_key: "high_high_medium_medium",
    profile_name: "Buzz Fountain",
    profile_description: "Gushes reactions, passes plenty, posts on schedule. A walking algorithm nudge.",
    profile_image: "/user_profiles/buzz_fountain.png",
  },
  {
    combination_key: "high_high_medium_high",
    profile_name: "Creator Crowd Surfer",
    profile_description: "Rides the waves of trends, talks a lot, posts a lot. Shares when the vibe is right.",
    profile_image: "/user_profiles/creator_crowd_surfer.png",
  },
  {
    combination_key: "high_high_high_low",
    profile_name: "Cheer and Share Titan",
    profile_description: "Engages and forwards with huge energy, never posts. The feed hears them anyway.",
    profile_image: "/user_profiles/cheer_and_share_titan.png",
  },
  {
    combination_key: "high_high_high_medium",
    profile_name: "Share and Flair Pro",
    profile_description: "Shares everything and cheers loudly, creates on the side. Party energy in every swipe.",
    profile_image: "/user_profiles/share_and_flair_pro.png",
  },
  {
    combination_key: "high_high_high_high",
    profile_name: "TikTok Addict",
    profile_description: "All dials at max, sleeps on 2x speed. The app might owe them rent.",
    profile_image: "/user_profiles/tiktok_addict.png",
  },
];
